# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku025-ffva1156-1-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/alif/_tools/_developed/conquest/test/AES/cb_aes_40/src/vivado/vivado.cache/wt [current_project]
set_property parent.project_path /home/alif/_tools/_developed/conquest/test/AES/cb_aes_40/src/vivado/vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/alif/_tools/_developed/conquest/test/AES/cb_aes_40/src/table.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top S4 -part xcku025-ffva1156-1-c


write_checkpoint -force -noxdef S4.dcp

catch { report_utilization -file S4_utilization_synth.rpt -pb S4_utilization_synth.pb }
