#Parameters that need to be changed depending on benchmark
IS_FLATTENED = true
TOP_MODULE 	= or1200_wb_biu
CLK_NAME 	= clk
RESET_NAME 	= rst
RESET_EDGE 	= 1
UNROLL_CYC	= 6
OBJ_SRC 	= ./src/or1200_wb_biu.v

