#Parameters that need to be changed depending on benchmark
IS_FLATTENED = true
TOP_MODULE 	= or1200_dc_fsm
CLK_NAME 	= clk
RESET_NAME 	= rst
RESET_EDGE 	= 1
UNROLL_CYC	= 50
OBJ_SRC 	= ./src/or1200_dc_fsm.v

