#Parameters that need to be changed depending on benchmark
IS_FLATTENED = true
TOP_MODULE 	= or1200_except
CLK_NAME 	= clk
RESET_NAME 	= rst
RESET_EDGE 	= 1
UNROLL_CYC	= 15
OBJ_SRC 	= ./src/or1200_except.v

