// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module OptimizationBarrier_22(
  input  [9:0]  io_x_reserved_for_future,	// src/main/scala/util/package.scala:268:18
  input  [43:0] io_x_ppn,	// src/main/scala/util/package.scala:268:18
  input  [1:0]  io_x_reserved_for_software,	// src/main/scala/util/package.scala:268:18
  input         io_x_d,	// src/main/scala/util/package.scala:268:18
                io_x_a,	// src/main/scala/util/package.scala:268:18
                io_x_g,	// src/main/scala/util/package.scala:268:18
                io_x_u,	// src/main/scala/util/package.scala:268:18
                io_x_x,	// src/main/scala/util/package.scala:268:18
                io_x_w,	// src/main/scala/util/package.scala:268:18
                io_x_r,	// src/main/scala/util/package.scala:268:18
                io_x_v,	// src/main/scala/util/package.scala:268:18
  output [9:0]  io_y_reserved_for_future,	// src/main/scala/util/package.scala:268:18
  output [43:0] io_y_ppn,	// src/main/scala/util/package.scala:268:18
  output [1:0]  io_y_reserved_for_software,	// src/main/scala/util/package.scala:268:18
  output        io_y_d,	// src/main/scala/util/package.scala:268:18
                io_y_a,	// src/main/scala/util/package.scala:268:18
                io_y_g,	// src/main/scala/util/package.scala:268:18
                io_y_u,	// src/main/scala/util/package.scala:268:18
                io_y_x,	// src/main/scala/util/package.scala:268:18
                io_y_w,	// src/main/scala/util/package.scala:268:18
                io_y_r,	// src/main/scala/util/package.scala:268:18
                io_y_v	// src/main/scala/util/package.scala:268:18
);

  assign io_y_reserved_for_future = io_x_reserved_for_future;
  assign io_y_ppn = io_x_ppn;
  assign io_y_reserved_for_software = io_x_reserved_for_software;
  assign io_y_d = io_x_d;
  assign io_y_a = io_x_a;
  assign io_y_g = io_x_g;
  assign io_y_u = io_x_u;
  assign io_y_x = io_x_x;
  assign io_y_w = io_x_w;
  assign io_y_r = io_x_r;
  assign io_y_v = io_x_v;
endmodule

